# Abdul Wahid Awan 20i-2367 J

# Libraries

In [1270]:
import pandas as pd
import numpy as np
import os
from itertools import chain
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold

# ECG DataSet

# PreProcessing

In [1271]:
parent=r'C:\Users\Abdul Wahid Awan\Downloads'
os.chdir(parent)

In [1272]:
df=pd.read_csv('ECG200_TRAIN.csv',delimiter='  ')

C:\Users\Abdul Wahid Awan\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

In [1273]:
df.rename(columns={'-1.0000000e+00':'Label'},inplace=True)

In [1274]:
# df.sort_values(by=['Label'],inplace=True,ascending=False)
df.reset_index(inplace=True)
df.drop(labels='index',inplace=True,axis=1)

In [1275]:
df

,Label,5.0205548e-01,5.4216265e-01,7.2238348e-01,1.4288852e+00,2.1365158e+00,2.2811490e+00,1.9362737e+00,1.4688900e+00,1.0088451e+00,...,9.3104294e-01,6.1029836e-01,6.3889427e-01,6.8467857e-01,5.8323764e-01,6.4052167e-01,7.0858515e-01,7.0501088e-01,7.1381545e-01,4.3376464e-01
0,1.0,0.147647,0.804668,0.367771,0.243894,0.026614,-0.274402,0.096731,-0.747731,-1.609777,...,-0.533503,-0.400228,0.176084,1.111768,2.438428,2.734889,1.736054,0.036857,-1.265074,-0.208024
1,-1.0,0.316646,0.243199,0.370471,1.063738,1.678187,1.759558,1.697717,1.612159,1.168188,...,0.764229,0.610621,0.552900,0.566786,0.604002,0.777068,0.812345,0.748848,0.818042,0.539347
2,-1.0,1.168874,2.075901,1.760141,1.606446,1.949046,1.302842,0.459332,0.516412,0.852180,...,0.419006,0.723888,1.323947,2.136488,1.746597,1.470220,1.893512,1.256949,0.800407,0.731540
3,1.0,0.648658,0.752026,2.636231,3.455716,2.118157,0.520620,-0.188627,0.780818,0.933775,...,-0.097869,-0.136787,-0.340237,-0.089441,-0.080297,-0.192584,-0.304704,-0.454556,0.314590,0.582190
4,1.0,0.404733,1.280859,2.515148,1.299519,1.453432,0.474275,-1.396562,-0.647081,0.431945,...,0.376469,0.277811,0.225676,0.159091,0.408354,0.540015,-0.027791,0.203476,0.346964,0.339185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,1.0,0.581277,0.876188,1.042767,1.796120,2.541399,2.246653,1.500387,1.031521,0.382672,...,1.002770,0.907869,0.916457,0.923975,0.767357,0.656223,0.762357,0.501373,-0.333336,-0.524546
95,-1.0,2.689017,2.708703,2.008381,2.235800,1.516982,0.029916,-0.561346,-0.793702,-0.979371,...,-0.136610,-0.072176,-0.082738,-0.138468,-0.120396,-0.089411,-0.243141,-0.119710,0.124042,0.273463
96,-1.0,0.197677,0.455417,0.973110,1.935956,2.259463,1.741341,1.158296,0.418241,-0.071605,...,0.482452,0.325569,0.247991,0.184127,0.050358,0.241988,0.331451,-0.120006,0.042423,0.343293
97,1.0,0.179500,1.038409,1.946421,2.705141,1.670706,-0.101167,-1.578876,-0.750906,0.175310,...,0.324323,0.330489,0.111953,0.448948,0.567132,0.136757,0.444768,0.151050,0.193378,0.451709
98,1.0,0.073124,0.776054,2.181336,3.440325,2.168475,0.497315,-0.924284,-1.499227,-0.679328,...,-0.058935,-0.130638,-0.347235,-0.177933,-0.060332,-0.347634,-0.447443,-0.066689,-0.178448,-0.256052

In [1276]:
df['Label'].value_counts()

 1.0    69
-1.0    30
Name: Label, dtype: int64

# K-Folds

In [1277]:
def split(k):
    temp1=df[df['Label']==1.0]
    new1=np.array_split(temp1,k)
    
    temp2=df[df['Label']==-1.0]
    new2=np.array_split(temp2,k)
    
    return new1,new2

In [1278]:
k=4
new1,new2=split(k)

In [1279]:
def k_folds():
    all_folds= new1
    for i in range(0,4):
         all_folds[i]=all_folds[i].append(new2[i])
    return all_folds

In [1280]:
all_folds=k_folds()

In [1281]:
train_folds=[[0,1,2],[1,2,3],[0,3,1],[0,2,3]]
test=[3,0,2,1]

In [1282]:
def K_Folds_Processing(k):
    x_train=pd.DataFrame()
    y_train=[]
    x_test=[]
    y_test=[]
    for i in range(0,k):
    #     Making Training and testing Folds
        print("\t\tK-Fold #",i+1)
        index=train_folds[i]
        j=index[0]
        k=index[1]
        l=index[2]
        x_train=pd.concat([all_folds[j],all_folds[k],all_folds[l]])
        y_train=x_train['Label']
        x_train.drop(labels='Label',axis=1,inplace=True)

        x_test=all_folds[test[i]]
        y_test=x_test['Label']
        x_test=x_test.loc[:, x_test.columns != 'Label']

    #     Model
        clf = tree.DecisionTreeClassifier()
        clf = clf.fit(x_train, y_train)

        y_pred=clf.predict(x_test)
        print('Accuracy:', accuracy_score(y_test, y_pred)*100)
        print("F1 Score : ",f1_score(y_test, y_pred, average='macro')*100)
        print('\n')

In [1283]:
K_Folds_Processing(k)

		K-Fold # 1
Accuracy: 79.16666666666666
F1 Score :  73.62637362637362


		K-Fold # 2
Accuracy: 84.61538461538461
F1 Score :  80.45112781954887


		K-Fold # 3
Accuracy: 91.66666666666666
F1 Score :  89.91596638655462


		K-Fold # 4
Accuracy: 72.0
F1 Score :  66.66666666666666

# SK Learn

In [1284]:
labels=df['Label']
df.drop(labels='Label',axis=1,inplace=True)

In [1285]:
kfolds = KFold(n_splits=4)
kfolds.get_n_splits(df)
i=0
for train_index, test_index in kfolds.split(df):
    print("\t\t K-Fold#",i+1)
    X_train, X_test = df.iloc[train_index], df.iloc[test_index]
    y_train, y_test = labels.iloc[train_index], labels.iloc[test_index]
    
    clf = tree.DecisionTreeClassifier()
    clf = clf.fit(X_train,y_train)
    
    y_pred=clf.predict(X_test)
    print('Accuracy:', accuracy_score(y_test, y_pred)*100)
    print("F1 Score : ",f1_score(y_test, y_pred, average='macro')*100)
    i+=1

		 K-Fold# 1
Accuracy: 76.0
F1 Score :  67.10526315789474
		 K-Fold# 2
Accuracy: 80.0
F1 Score :  74.01247401247402
		 K-Fold# 3
Accuracy: 84.0
F1 Score :  78.0701754385965
		 K-Fold# 4
Accuracy: 79.16666666666666
F1 Score :  75.75757575757575

# Medicine Dataset

# PreProcessing

In [1286]:
df=pd.read_csv('Medicine-Updated.csv')

In [1287]:
columns=df.columns
for i in columns:
    le=LabelEncoder()
    df[i]=le.fit_transform(df[i])

In [1288]:
df

     Intensity  Diagnosis  Type  History  Temp  BP  Age  Name of Medicine
0           23         41     3        1     1   0   15                12
1           23         25     3        7     0   0   16                13
2            5         40     3        1     1   0   17                14
3           29         48     3        2     0   1   18                15
4           22         58     3        0     0   0   19                18
..         ...        ...   ...      ...   ...  ..  ...               ...
100         11          7     1        0     0   0   95                22
101         11          7     1        3     0   0   96                55
102         26          7     1        0     0   0   97                56
103          0          7     1        4     0   0   98                82
104         27          7     1        1     0   0   99                98

[105 rows x 8 columns]

# SK Learn

In [1289]:
y=df['Name of Medicine']
df.drop(labels='Name of Medicine',axis=1,inplace=True)